import {
  DmSans,
  spanLight,
  spanLightItalic,
  spanRegular,
  spanSemiBold,
  spanSemiBoldItalic,
  spanBold,
  spanBoldItalic,
  LexendZetta,
} from "@/fonts/font";
import "@/styles/bootstrap.min.css";
import "@/styles/global.css";
import Script from "next/script";
import Header from "@/components/general/Header";
import Footer from "@/components/general/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${LexendZetta.variable} ${DmSans.variable} ${spanLight.variable} ${spanLightItalic.variable} ${spanRegular.variable} ${spanSemiBold.variable} ${spanSemiBoldItalic.variable} ${spanBold.variable} ${spanBoldItalic.variable}`}
      >
        <Header />
        {children}
        <Footer />
        <Script
          strategy="afterInteractive"
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
          crossorigin="anonymous"
        />
      </body>
    </html>
  );
}
